### ISSUE TITLE
Can you add a X header for requests coming through the CLI ?

### ISSUE THREAD

**Issue by pastelsky** [AdrieanKhisbe/bundle-phobia-cli#1]
Hi Adriean, 
Thanks for making this CLI app.

I've been getting some suspicious traffic lately on bundlephobia.com, and finding it hard to track down the origin of these requests. The number of requests far exceed the number of users reported by Google Analytics. Do you think you could add a `X-<something>` header so that I can track requests originating from this CLI ?

**Comment by AdrieanKhisbe** [comment]
Of course @pastelsky. Will due so.
Not the CLI is used yet, but yes I made several batch request mainly to lodash.
I will add a `X-header`, do you have any preference X- standard header we could use?

**Comment by AdrieanKhisbe** [comment]
@pastelsky I went for customising the user agent:
https://github.com/AdrieanKhisbe/bundle-phobia-cli/commit/28023eb1ad644a81b3482b3f87ff7bb4cfe0215d

I made some query with it. 
Tell me if iit's good for your and I'll make a patch release :)

**Comment by pastelsky** [comment]
Thanks, that should be helpful. I just want to be sure that running
multiple such CPU intensive queries programmatically doesn't saturate the
server.

**Comment by AdrieanKhisbe** [comment]
Et voilà! 
just release the 0.5.1 https://github.com/AdrieanKhisbe/bundle-phobia-cli/commit/bee155652b87047bdd340f64a78fd22f6ea296b9. available on npm.

If you have other suggestions or request, please do ask :)
