### ISSUE TITLE
Feature request: support the `--registry` option

### ISSUE THREAD

**Issue by fed135** [AdrieanKhisbe/bundle-phobia-cli#14]
Would be great to have the option to target specific registries.
This option can be forwarded to npm and yarn easily.

**Comment by AdrieanKhisbe** [comment]
@fed135 Sorry for the late answer.

After checkying, it's already supported by the cli!

Indeed, every options that does not avec `bundle-phobia` cli is forwarded to the underlying `npm`

**Comment by fed135** [comment]
Great, thanks!

**Comment by AdrieanKhisbe** [comment]
you're welcome.
If ever you want the `yarn` to be supported for install, open an issue and i'll see what I can do
