### ISSUE TITLE
Human readable size outputs

### ISSUE THREAD

**Issue by transitive-bullshit** [AdrieanKhisbe/bundle-phobia-cli#2]
package-size's output is more readable, making use of [bytes](https://github.com/visionmedia/bytes.js).

E.g., `65.69 KB  (17.5 KB gzipped)` compared to  `56661B (15233B gzipped)`

Just a minor nit :)

**Comment by AdrieanKhisbe** [comment]
Yes indeed you're right.
I might have looked into it at some point, but I don't remember.

Will try to implement it, but feel free to propose a PR :)

**Comment by AdrieanKhisbe** [comment]
@transitive-bullshit Thats good, I just release 0.6.0 with your changes.
Thanks !! :)
