### ISSUE TITLE
Size of package returns null on install

### ISSUE THREAD

**Issue by tkadlec** [AdrieanKhisbe/bundle-phobia-cli#25]
When I install a package with a `max-overall-size` option specified, the package install fails every time because `bundle-phobia` is seeing the package size as `null`

For example, given the following in my `package.json`:

```
...
"bundle-phobia": {
    "max-size": "20kB",
    "max-overall-size": "50kB"
  },
```

When I run `bundle-phobia-install react`, I see:

```
ℹ Applying a size limit of 20KB from argv and overall size limit of 50KB from argv

✖ Could not install for following reasons:
✔ react: was individually ok to install
✖ global constraint is not respected: overall size after install would be over threshold (0B installed + null > 50KB)
bundle-phobia-install failed: Install was canceled.
```
From what I can tell, the size does get returned when bundle-phobia fetch's the package (`fetchPackageStats`), but never gets set for `toInstallStats`. Adding a `console.info(toInstallStats)` [here](https://github.com/AdrieanKhisbe/bundle-phobia-cli/blob/master/src/install.js#L136) results in:

```
{ size: undefined, gzip: undefined, dependencyCount: undefined }
```

**Comment by AdrieanKhisbe** [comment]
Thanks @tkadlec for the investigation.
I have the fix incoming in #26, and will publish a patch once merge

**Comment by AdrieanKhisbe** [comment]
@tkadlec You can try `bundle-phobia-cli@0.14.6` :)

**Comment by tkadlec** [comment]
Worked perfectly! Thanks!
