### ISSUE TITLE
Can this be used as a Node API instead of as a CLI tool?

### ISSUE THREAD

**Issue by saavannanavati** [AdrieanKhisbe/bundle-phobia-cli#27]
This is really useful as a CLI tool but I'm interested in being able to use this directly via JavaScript, to automate some tasks, by importing the module and making calls directly to the package. Is this possible?

**Comment by saavannanavati** [comment]
It can, the functions are exported in index.js.

Closing this issue since it's solved

**Comment by AdrieanKhisbe** [comment]
Glad you found the answer @saavannanavati =)
