### ISSUE TITLE
Packages with periods in the name say version range is not resolvable when using a pinned version

### ISSUE THREAD

**Issue by bbugh** [AdrieanKhisbe/bundle-phobia-cli#35]
Hi! :wave: Thanks for this great package.

Running with the --package command isn't working with `ahoy.js` and `chart.js` for some reason. I'm guessing maybe it's the period? I tested with the `asn1.js` package as well (which we're not using) and it also broke.

```
>> bundle-phobia --package package.json
ℹ @sentry/browser (5.26.0) has 4 dependencies for a weight of 69.07KB (19.28KB gzipped)
ℹ @sentry/integrations (5.26.0) has 4 dependencies for a weight of 56.35KB (16.66KB gzipped)
✖ resolving ahoy.js@^0.3.5 failed: Specified version range '^0.3.5' is not resolvable
bundle-phobia failed: Specified version range '^0.3.5' is not resolvable
```

Same thing with `chart.js` if I remove ahoy:

```
bundle-phobia --package package.json                [3:59:33 PM]
✖ resolving chart.js@^2.9.3 failed: Specified version range '^2.9.3' is not resolvable
bundle-phobia failed: Specified version range '^2.9.3' is not resolvable
```

Running it for ahoy alone shows 0.3.7:

```
>> bundle-phobia ahoy.js
ℹ ahoy.js (0.3.7) has 1 dependencies for a weight of 6.83KB (2.82KB gzipped)
```

Running it **without** the pin on 0.3.5 works:

```
>> bundle-phobia ahoy.js@0.3.5
ℹ ahoy.js (0.3.5) has 1 dependencies for a weight of 6.71KB (2.77KB gzipped)
```

Running it **with** the pin on 0.3.5 fails:

```
bundle-phobia ahoy.js@^0.3.5
✖ resolving ahoy.js@^0.3.5 failed: Specified version range '^0.3.5' is not resolvable
bundle-phobia failed: Specified version range '^0.3.5' is not resolvable
```

Removing `ahoy.js` and `chart.js` from `package.json` allows it to run successfully. My hypothesis is that it's the period causing issues.

**Comment by AdrieanKhisbe** [comment]
Thanks @bbugh, also for the very detailed bug report :)

I would say that could be linked to a regex, and maybe pin `^` special meaning.
That should'nt be complicated, I'll have a look and try to fix it shortly

**Comment by AdrieanKhisbe** [comment]
In the end was related to another `.` dot special meaning issue.

Opened a PR, will likely publish a patch very quickly

**Comment by AdrieanKhisbe** [comment]
I just released the patch version `bundle-phobia-cli@0.14.10`, tell me @bbugh once you've tried it :)

**Comment by bbugh** [comment]
It works great! Thanks so much for the update.

**Comment by AdrieanKhisbe** [comment]
Cool :) 
Thanks you too for your update @bbugh !
