### ISSUE TITLE
automatically run bundle-phobia on npm-install/update

### ISSUE THREAD

**Issue by staabm** [AdrieanKhisbe/bundle-phobia-cli#5]
would be great to get a report about bundle-sizes/bundle-size-changes on npm install/update without the need to actually invoke `bundle-phobia <package-name>` directly.

that way, the developer immediately sees the data at hand while working and cant forget to check the bundlesize when installing/updating

**Comment by CollinRea** [comment]
you could definitely do this with a bash function if you are comfortable doing that.
something like...

```
bundle-phobia-install () {
    bundle-phobia "$1"
    read -p "Continue (y/n)?" CONT
    if [ "$CONT" = "y" ]; then
        echo "starting install";
        npm install "$1"
    else
        echo "canceling install";
    fi
}

```

I haven't tested this code but something like this would theoretically run bundle-phobia with the given package name and prompt for continue or not.

**Comment by staabm** [comment]
thx
